### ISSUE TITLE
Bug in streamstatus.get_listener_count

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/Hanyuu-sama#15]
There is a bug in streamstatus.get_listener_count. The url that's used to get the status is "http://streamX.r-a-d.io:PORT/", however, this breaks when the status page is a frameset. The proper URL should be "http://streamX.r-a-d.io:PORT/status.xsl".

The reason I'm making an issue and not fixing this myself is because Eclipse is shit and I can't pull from the repo, and I'm too lazy to reclone.

**Comment by ameliaikeda** [comment]
git checkout. also it should be "RELAY_NAME.BASE_NAME:PORT/MOUNT.split(".")[0].xspf" using XML

**Comment by ameliaikeda** [comment]
Reason for this is because status.xsl is branch-dependent and the only thing that stays consistent between forks is the XML

**Comment by Bevinsky** [comment]
The reason for using the HTML instead of the XML was because the original author of streamstatus wasn't aware of the XML when that module was written, and I didn't feel like correcting it.

Though, I do wonder... the same parser ought to work on the XML, with a few modifications. Probably gives simpler code too. I'll make an issue.

Also, the XML doesn't require an admin pass to access it. That's another added bonus. As I said, we only found this out when we were working on the proxy.
