### ISSUE TITLE
Rewrite streamstatus to use XML instead of HTML

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/Hanyuu-sama#16]
The header explains it all. The streamstatus currently uses the HTML of the status page and the HTML of the client list page in the admin interface to determine listener count and such. This is probably a Bad Idea for various reasons, but we just haven't gotten around to fixing it (as with all things r/a/dio).

**Comment by ameliaikeda** [comment]
Commit c43060f fixes this
