### ISSUE TITLE
Queue is only displayed for Hanyuu

### ISSUE THREAD

**Issue by ameliaikeda** [R-a-dio/Hanyuu-sama#23]
Title says it all. watcher.py doesn't monitor the file, and several DJs don't use queue.

**Comment by Wessie** [comment]
The monitoring is actually being done, none uses it though. Set a flag to disable the `.queue` command instead.

**Comment by ameliaikeda** [comment]
queue is no longer valid as no DJs use SAM any more due to lack of UTF-8 support.

**Comment by ameliaikeda** [comment]
#49 is the continuation of this.
