### ISSUE TITLE
Add plugs for new login system

### ISSUE THREAD

**Issue by ameliaikeda** [R-a-dio/Hanyuu-sama#3]
hanyuu needs to be able to read the authkey from the new users system, verify that the nick she is messaged by is +R (tip: /msg nickserv STATUS USER), and then associate all faves from that nick with the new user (new table that literally just uses the index on that nick (or id, pls) and pulls the faves instead)
This will change the faves queries, but not the way they work.

The new table will be a simple link:

```
+----+------------------+----------------+-------------------------+------+
| id | email            | nick_key       | auth_token              | nid  |  
+----+------------------+----------------+-------------------------+------+
| 1  | hiroto@hiroto.eu | ab2f1af71a2f5a | GOOGLE21SDFAS&R*$£)$TR/ | 14   |
| 2  | nutcase@web      | avgfasb81a2f5a | GOOGLE21SDFAS&ASDF4368/ | NULL |
+----+------------------+----------------+-------------------------+------+
```

Where `1` here is a linked account and `2(nid)` is `null` and hence unlinked

Unlinked people will also be in the current faves system, but their "nickname" will be their email.
This is one hell of a convoluted system and i just want to migrate the current stuff to a new faves system pretty badly.

**Comment by Wessie** [comment]
``` python
class RadioUser(User):
    google_token = models.CharField(limit=50, null=True)
    nickname = models.ForeignKey(Nicknames)
```

That should satisfy your needs.

**Comment by Wessie** [comment]
These were site-account plans, we decided to not have these.
