### ISSUE TITLE
Restrictions on commands for non-admins

### ISSUE THREAD

**Issue by ameliaikeda** [R-a-dio/Hanyuu-sama#5]
At current,  your development is focused on restricting the administration from performing any utility functions at all. Try and stop this and instead offer options for higher privileges to use these easily instead of bitching and removing them and then going on a power trip. 
Also,  trying to hard code restrictions while a root user has access to the console is futile, and just an annoyance. 
See: queue manipulation, request control

**Comment by Bevinsky** [comment]
The main reason for locking down functionality is to prevent said admins from going on power trips.

Also, hypocrisy much?
