### ISSUE TITLE
IRC commands have a longer than usual response time

### ISSUE THREAD

**Issue by ameliaikeda** [R-a-dio/Hanyuu-sama#54]
Been noticing this a lot, recently, but hanyuu's `.lucky`, `.r` and `.np` commands seem to have excessive lag above what would be expected from IRC. Could do with some investigating.

**Comment by Wessie** [comment]
I can't reproduce the `.lucky` and `.request` lags, the `.np` lag is due to streamstatus now being laggy most likely.

**Comment by Wessie** [comment]
This was indeed caused by a slower `streamstatus` this has been mostly reduced and will be fully fixed in `1.3`.
