### ISSUE TITLE
Removal of commands that give unfair advantage

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/Hanyuu-sama#6]
I think it would be prudent to remove and preempt the creation of commands like `Queue().bump()`, as they serve no real purpose other than letting admins get requests in over other requesters.

I'll admit, the reason I added the command in the first place was to put my requests first, but I've come to the conclusion that it's better to remove these commands instead of constructing any semblance of responsibility among the staff, as this is clearly an impossible task.

This command also causes strife and friction within the developer circle, which is another reason to have it and similar, future commands removed.

**Comment by Wessie** [comment]
These shall be removed in the transfer to the new database/website. We also need to make sure to limit access to the Queue table in the administration interface.

**Comment by Wessie** [comment]
This is a non-issue again.
