### ISSUE TITLE
Hanyuu never checks if a user is registered.

### ISSUE THREAD

**Issue by ameliaikeda** [R-a-dio/Hanyuu-sama#65]
Hanyuu never verifies if a user is registered when using user-specific commands. `.fave` and `.unfave` are no issue here; they would utterly crucify performance, but the `SEND CODE` and the (new) `REGISTER KEY` private commands should ideally be checked with the nickserv status command. Keep in mind this makes us Rizon-specific.

```
<stuff>:PRIVMSG NickServ :STATUS <nick>
PRIVMSG :NickServ :<nick> <0|1|2|3>
```

**Comment by Wessie** [comment]
Fixed by #67 in the 1.3 branch.
