### ISSUE TITLE
Excess flood on IRC

### ISSUE THREAD

**Issue by Wessie** [R-a-dio/Hanyuu-sama#8]
Hanyuu-sama is capable of Excess flooding herself when icecast tags are send it rapid succession as demonstrated by Skye`rackloy today.

She will excess flood herself after a continues abuse of around a minute of a song with 17 favorites.

This most likely means we don't do sufficient enough throttling in the IRC library.

**Comment by Bevinsky** [comment]
Commit 2e00ebaf26 closes this issue
