### ISSUE TITLE
Extend the .fave command to allow .fave next

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/Hanyuu-sama#9]
Someone in the IRC wants a `.fave next` command that lets you fave the song that's next in the queue.

I don't really see the point of this, since it's rather dangerous to have this while DJs are streaming (most DJs do not use queue and queue stays even after Hanyuu stops streaming [this will be fixed with the new DB] so there could be stale entries in the queue, resulting in incorrect faving by people who don't realize this). It would probably only be usable while Hanyuu is streaming, in which case you might as well use `.fave <id>`.

Any comments?

**Comment by ameliaikeda** [comment]
Eh, not worth it; too dangerous.
